### ISSUE TITLE
 Argument of type .... is not assignable to parameter of type 'Har'.

### ISSUE THREAD

**Issue by ishandutta2007** [readmeio/fetch-har#409]
```
import fetchHAR from 'fetch-har'
const har = {
  "log": {
    "entries": [{
        ...
        ...
      }
    ]
  }
};
let  response = await fetchHAR(har);
console.log(response.status);
```

Error:

`src/app/bots/xyz-webapp/index.ts:667:35 - error TS2345: Argument of type '{ log: { entries: { _initiator: { type: string; stack: { callFrames: { functionName: string; scriptId: string; url: string; lineNumber: number; columnNumber: number; }[]; parent: { description: string; callFrames: { ...; }[]; parent: { ...; }; }; }; }; ... 10 more ...; timings: { ...; }; }[]; }; }' is not assignable to parameter of type 'Har'.
`

**Comment by erunion** [comment]
Hey! I'm not sure what `stack` is in the error for the HAR you're using but that's not a part of the [@types/har-format](https://www.npmjs.com/package/@types/har-format) package that we use here.
